version: "3"
services:
  moviedb_server:
    container_name: moviedb_server
    build: .
    ports:
      - 5000:5000
  database:
    image: mysql
    container_name: database
    restart: always
    volumes:
      - moviedb_vol:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: moviedb@password
      MYSQL_DATABASE: moviedb
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8888:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: moviedb@password
      PMA_HOST: database
volumes:
  moviedb_vol:
    driver: local
